---
description: "#{repo}"
builds:
- platform: "centos7"
  arch: "amd64"
  asset_filename: "#{repo}_#{version}_centos7_linux_amd64.tar.gz"
  sha_filename: "#{repo}_#{version}_sha512-checksums.txt"
  filter:
  -  "entity.system.os == 'linux'"
  -  "entity.system.arch == 'amd64'"
  -  "entity.system.platform_family == 'rhel'"
  -  "entity.system.platform_version.split('.')[0] == '7'"
- platform: "debian9"
  arch: "amd64"
  asset_filename: "#{repo}_#{version}_debian9_linux_amd64.tar.gz"
  sha_filename: "#{repo}_#{version}_sha512-checksums.txt"
  filter:
  -  "entity.system.os == 'linux'"
  -  "entity.system.arch == 'amd64'"
